### ISSUE TITLE
Application stop when the plugin run

### ISSUE THREAD

**Issue by caocuongajax** [nchutchind/Vitamio-Cordova-Plugin#11]
I has a problem with this plugin, when I run plugin then application stopped. Could you so me solution?
This is information from "ionic info"
Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 

Thanks

**Comment by rvolution** [comment]
@caocuongajax i am facing the same problem using almost the same setup, did you solve it?

**Comment by caocuongajax** [comment]
@rvolution I don not still solve it.

**Comment by zhuxianchen** [comment]
android api over 22 not work ,so  you can use 22 ,it work ok.
